# Generated by Django 5.0.4 on 2024-04-07 16:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_start', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesstoken',
            name='currently_in_use',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accesstoken',
            name='last_used_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
