# Generated by Django 5.0.4 on 2024-04-07 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_start', '0002_accesstoken_currently_in_use_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesstoken',
            name='memo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
